name: Deploy

on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Debug release tag
        run: |
          echo "Tag: ${{ github.event.release.tag_name }}"

      - name: check out codebase
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: verify
        run: |
          cat ./changes.md
